drf_jwt/api/urls.py
from django.urls import path, include
#APP
from rest_framework_simplejwt.views import TokenVerifyView
from api.views.authentication_views.auth_views import LoginView, ReissueTokenView, LogoutView

from api.views.test_views.test_views import TestView

app_name='api'
urlpatterns = [
    path('login/', LoginView.as_view()),
    path('token/verify/', TokenVerifyView.as_view()), #토큰 검증 ..
    path('token/refresh/', ReissueTokenView.as_view()),
    path('logout/', LogoutView.as_view()),

    path('test/', TestView.as_view()),
]

drf_jwt/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('api/', include('api.urls')),
    path('system-manage/', include('system_manage.urls')),
]

drf_jwt/system_manage/urls.py
from django.urls import path, include
from system_manage.views.system_manage_views.auth_views import HomeView, LoginView
from system_manage.views.system_manage_views.access_manage_views import AccessManageView, GroupManageView
from system_manage.views.system_manage_views.permission_manage_views import AccessPermissionManageView

app_name='system_manage'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    # 권한 접근 관리

    path('access-manage/', AccessManageView.as_view(), name='access_manage'),
    path('group-manage/', GroupManageView.as_view(), name='group_manage'),
    path('permission-manage/', AccessPermissionManageView.as_view(), name='permission_manage'),

]

drf_jwt/website/urls.py
from django.urls import path, include
from website.views.authentication_views.auth_views import HomeView, TestView


app_name='website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('test/', TestView.as_view(), name='test'),
]

drf_jwt/system_manage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db.models.query_utils import Q
# Create your models here.

class AccessPermissionManager(models.Manager):
    def get_queryset(self):
        return super(AccessPermissionManager, self).\
            get_queryset().filter(
                Q(content_type=AccessPermission.PERMISSION_TYPE.READ) |
                Q(content_type=AccessPermission.PERMISSION_TYPE.WRITE)
            )


class AccessPermission(Permission):
    """Proxy model for permission"""

    class Meta:
        proxy = True

    class __PERMISSION_TYPE:
        def get_all_permissions(self):
                    """Get list of all permissions."""
                    return [
                        self.READ,
                        self.WRITE
                    ]

        @property
        def WRITE(self):
            return ContentType.objects.get_or_create(
                app_label='write',
                model="write_permission",
            )[0]

        @property
        def READ(self):
            return ContentType.objects.get_or_create(
            app_label='read',
            model='read_permission',
            )[0]

    PERMISSION_TYPE = __PERMISSION_TYPE()
    objects = AccessPermissionManager()
    
    def save(self, *args, **kwargs):
        # Check Permission Type.
        if self.content_type not in self.PERMISSION_TYPE.get_all_permissions():
            raise ValueError('Not permitted Permission Type.')
        
        # ct, created = ContentType.objects.get_or_create(
        #     model=self._meta.verbose_name, app_label=self._meta.app_label,
        # )

        #self.content_type = ct
        super(AccessPermission, self).save(*args)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
  
    class Meta:
        db_table='auth_profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

drf_jwt/website/models.py
from django.db import models

# Create your models here.

drf_jwt/system_manage/templates/admin_pagination.html
<!-- 페이징처리 시작 -->
<div id="paging">
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" onclick="page('{{ page_obj.previous_page_number }}')" style="cursor: pointer;">이전</a>
            <!-- href로 뎁스 설정 -->
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in pagelist %}
            {% if page_number == page_obj.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_number }}</a>
            </li>
            {% else %}
              {% if page_number == page_obj.paginator.ELLIPSIS %}
              <li class="page-item"><span class="page-link" style="cursor: pointer;">{{ page_number }}</span></li>
              {% else %}
              <li class="page-item">
                <a class="page-link" onclick="page('{{page_number}}')" style="cursor: pointer;">{{ page_number }}</a>
              </li>
              {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" onclick="page('{{ page_obj.next_page_number }}')" style="cursor: pointer;">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
  </div>

drf_jwt/system_manage/templates/system_manage/access_manage.html
{% extends "layouts/system_base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/css/bootstrap-select.min.css">
{% endblock stylesheets %}

{% block main %}
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Access Manage</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'system_manage:home' %}">Home</a></li>
            <li class="breadcrumb-item">Access Manage</li>
            <li class="breadcrumb-item active">User</li>
          </ol>
        </nav>
    </div><!-- End Page Title -->
  
      <section class="section">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Access Manage</h5>
            <p>그룹을 생성 및 삭제하고 그룹의 권한을 관리할 수 있습니다.</p>
            <div>
                <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal_create_group" onclick="clearCreationModal();">Create Group</button>
            </div>
          </div>
        </div>
        <div class="card" >
          <div class="card-header">
            <b>상세 검색</b>
          </div>
          <div class="card-body">
            <div class='row mb-3 mt-3'>
                <div id='divGroupsSelect' class='col-md-3'>
                  <select id='groupsSelect' class="form-control selectpicker" data-style-base='form-control' data-style='' data-live-search="true" title="사용자 그룹을 지정하세요." name='groups' onchange="getGroupPermissionList();">
                      {% if groups %}
                          {% for group in groups %}
                          <option value="{{ group.id }}" {% if selected_group == group %} selected {% endif %}>{{ group.name }}</option>
                          {% endfor %}
                      {% endif %}
                  </select>
                </div>
                <button type="button" id='btn_grp_delete' class='btn btn-danger ml-3 col-md-2' onclick="deleteGroup('{{selected_group.id}}');">그룹 삭제</button>
            </div>
            {% if selected_group %}
            <div class="row">
                <form id="search-form" class="p-2" method="get" action="" onsubmit="return false">
                    <input type="hidden" name="group_id" value="{{selected_group.id}}">
                    <div class="row mb-2">
                      <label for="item" class="col-sm-2 col-form-label">검색 분류</label>
                      <div class="col-sm-8">
                          <div class="input-group">                   
                            <select class="form-select" id="search_type" name="search_type">
                              {% if search_type == 'name' %}
                              <option value="name" selected>권한 이름</option>
                              {% else %}
                              <option value="name">권한 이름</option>
                              {% endif %}
                              {% if search_type == 'codename' %}
                              <option value="codename" selected>코드</option>
                              {% else %}
                              <option value="codename">코드</option>
                              {% endif %}
                            </select>
                          <input class="form-control" type="text" id="search_keyword" name="search_keyword" placeholder="Search Keword" value="{{search_keyword}}" style="width:50%">
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="text-center">
                          <button type="submit" id="btn-search" class="btn btn-primary">검색</button>
                          <a id="btn-initial" class="btn btn-outline-primary" href="{% url 'system_manage:access_manage' %}">초기화</a>
                      </div>
                    </div>
                  </form>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row justify-content-between">
                    <div class="col-auto">
                      <h5 class="card-title">권한 목록</h5>
                    </div>
                </div>
                <table class='table table-hover'>
                    <thead>
                      <tr>
                        <th></th>
                        <th>권한 ID</th>
                        <th>권한 이름</th>
                        <th>Code</th>
                        <th>Access Type</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% if page_obj %}
                          {% for i in page_obj %}
                          <tr>
                            <td>
                                <div class="form-check form-switch">
                                    <input type="checkbox" class="form-check-input" id="Perm{{ i.id }}"  onchange="setGroupPermission('{{ i.id }}', '{{selected_group.id}}')" {% if i.hasPerm == True %} checked {% endif %}>
                                </div>
                            </td>
                            <td>{{ i.id }}</td>
                            <td>{{ i.name }}</td>
                            <td>{{ i.codename }}</td>
                            <td>{{ i.content_type.app_label}}</td>
                          </tr>
                          {% endfor %}
                      {% else %}
                      <tr>
                          <td colspan="5">데이터가 없습니다.</td>
                      </tr>
                      {% endif %}
                    </tbody>
                  </table>
                  {% include 'admin_pagination.html' %}
            </div>    
        </div>
      </section>
      <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modal_create_group" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">새 그룹(role) 생성</h4>
                    <button aria-hidden="true" data-bs-dismiss="modal" class="close btn" type="button">&times;</button>
                </div>
                <div id='divCreateGroup' class="modal-body" align='right'>
                  <input type="text" class="form-control" id="groupNameCreate" placeholder="그룹(role) 이름"/>
                  <br>
                  <br>
                  <button type="button" class="btn btn-success" onclick="createGroup();">생성</button>
                  
                  <span id="error_msg" style="margin-left:20px;color:#FF6600;"></span>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/js/bootstrap-select.min.js"></script>
<script src="{% static 'js/pagination/script_pagination.js' %}"></script>
<script src="{% static 'system/js/system_manage/script_group_manage.js' %}"></script>
<script src="{% static 'system/js/system_manage/script_access_manage.js' %}"></script>
{% endblock javascripts %}

drf_jwt/system_manage/templates/system_manage/admin_main.html
{% extends "layouts/system_base.html" %}
{% load static %}

{% block main %}
<main id="main" class="main">
</main>
{% endblock %}

drf_jwt/system_manage/templates/system_manage/permission_manage.html
{% extends "layouts/system_base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/css/bootstrap-select.min.css">
{% endblock stylesheets %}

{% block main %}
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Permission Manage</h1>
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'system_manage:home' %}">Home</a></li>
            <li class="breadcrumb-item">System Manage</li>
            <li class="breadcrumb-item active">Permission</li>
          </ol>
        </nav>
    </div><!-- End Page Title -->
      <section class="section">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Permission Manage</h5>
            <p>사용자에게 부여할 권한을 검색, 생성, 수정 및 삭제할 수 있습니다.</p>
            <div>
              <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal_create_menu" onclick="clearCreationModal();">Create Permission</button>
            </div>
          </div>
        </div>
        <div class="card" >
          <div class="card-header">
            <b>상세 검색</b>
          </div>
          <div class="card-body">
            <div class="row">
                <form id="search-form" class="p-2" method="get" action="">
                    <div class="row mb-2">
                      <label for="item" class="col-sm-2 col-form-label">검색 분류</label>
                      <div class="col-sm-8">
                          <div class="input-group">                   
                            <select class="form-select" id="search_type" name="search_type">
                              {% if search_type == 'name' %}
                              <option value="name" selected>권한 이름</option>
                              {% else %}
                              <option value="name">권한 이름</option>
                              {% endif %}
                              {% if search_type == 'codename' %}
                              <option value="codename" selected>코드</option>
                              {% else %}
                              <option value="codename">코드</option>
                              {% endif %}
                            </select>
                          <input class="form-control" type="text" id="search_keyword" name="search_keyword" placeholder="Search Keword" value="{{search_keyword}}" style="width:50%">
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="text-center">
                          <button type="submit" id="btn-search" class="btn btn-primary">검색</button>
                          <a id="btn-initial" class="btn btn-outline-primary" href="{% url 'system_manage:permission_manage' %}">초기화</a>
                      </div>
                    </div>
                  </form>
            </div>
          </div>
        </div>
        <div class="card mb-3" >
          <div class="card-body">
            <div class="row justify-content-between">
                <div class="col-auto">
                  <h5 class="card-title">권한 목록</h5>
                </div>
            </div>
            <table class='table table-hover' id='dataTable' width='100%' cellspacing='0'>
              <thead>
              <tr>
                <th class='col-md-1'>권한 ID</th>
                <th class='col-md-1'>권한 이름</th>
                <th class='col-md-1'>Code</th>
                <th class='col-md-1'>Access Type</th>
                <th scope='col' class='col-md-2'></th>
              </tr>
              </thead>
              <tbody>
              {% if page_obj %}
              {% for i in page_obj %}
              <tr id='row{{i.id}}'>
                <td id='permId{{i.id}}' name='id' data-value='{{ i.id }}'>{{ i.id }}</td>
                <td id='permName{{i.id}}'name='name' data-value='{{ i.name }}'>{{ i.name }}</td>
                <td id='permCodename{{i.id}}' name='codename' data-value='{{ i.codename }}'>{{ i.codename }}</td>
                <td id='permType{{i.id}}' name='content_type_id' data-value='{{ i.content_type_id }}'>{{ i.content_type.app_label}}</td>
                <td align='right'>
                  <button type="button" class='btn btn-warning' data-bs-toggle="modal" data-bs-target="#modal_update_menu" onclick="clearUpdateModal('{{i.id}}');">수정</button>
                  <button type="button" id='btn_mode{{ i.id }}' class='btn btn-danger' onclick="deleteMenu('{{i.id}}');">삭제</button>
                </td>
              </tr>
              {% endfor %}
              {% else %}
              <tr>
                <td colspan='5'>생성된 메뉴(권한)가 없습니다.</td>
              </tr>
              {% endif %}
              </tbody>
            </table>
            {% include 'admin_pagination.html' %}
            </div>
        </div>
      </section>
</main>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modal_create_menu" class="modal fade">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title">새 메뉴 생성</h4>
              <button aria-hidden="true" data-bs-dismiss="modal" class="close btn" type="button">&times;</button>
          </div>
          <div class="modal-body" align='right'>
              <input type="text" class="form-control" id="name" placeholder="새 메뉴(권한) 이름"/>
              <br>
              <input type="text" class="form-control" id="codename" placeholder="Code" oninput="updateUrlText(this, 'create_url_alerter');">
                  <div id='create_url_alerter'><i class="fa" aria-hidden="true" ></i>접근 권한을 설정할 Code를 입력하세요.</div>
              </input>
              <br><br>
              <button type="button" data-dismiss="modal" class="btn btn-success" onclick="createMenu();">생성</button>
              
              <span id="error_msg" style="margin-left:20px;color:#FF6600;"></span>
          </div>
      </div>
  </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modal_update_menu" class="modal fade">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title">메뉴 수정</h4>
              <button aria-hidden="true" data-bs-dismiss="modal" class="close btn" type="button">&times;</button>
          </div>
          <div class="modal-body" align='right'>
              <input type="hidden" class="form-control" id="id_update" />
              <input type="text" class="form-control" id="name_update" placeholder="메뉴(권한) 이름"/>
              <br>
              <input type="text" class="form-control" id="codename_update" placeholder="Code" oninput="updateUrlText(this, 'update_url_alerter');">
                  <div id='update_url_alerter'><i class="fa" aria-hidden="true" ></i>접근 권한을 설정할 Code를 입력하세요.</div>
              </input>
              <br><br>
              <button type="button" data-dismiss="modal" class="btn btn-success" onclick="updateMenu();">수정</button>
              
              <span id="update_error_msg" style="margin-left:20px;color:#FF6600;"></span>
          </div>
      </div>
  </div>
</div>

{% endblock %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta2/dist/js/bootstrap-select.min.js"></script>
<script src="{% static 'js/pagination/script_pagination.js' %}"></script>
<script src="{% static 'system/js/system_manage/script_permission_manage.js' %}"></script>
{% endblock javascripts %}

drf_jwt/templates/home.html
<h1>Main Page</h1>
<div>
    {% csrf_token %}
    
    {% if user %}
        <button onclick="logout()">logout</button>
    {% else %}
        <button onclick="location.href='/system-manage/login/'">login</button>
    {% endif %}
    <br>
    <br>
    <input type="email" id="email">
    <button type="button" onclick="test()">submit</button>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="/static/js/authentication/jwt.js"></script>
<script>
    let auth = authentication();
    function test(){
        if (!confirm("구매하시겠습니까?")) {
            return false;
        }
        let access_token = getCookie("access_token");
        $.ajax({
            type: "POST",
            url: "/api/test/",
            headers: {
                'Authorization': `Bearer ${access_token}`,
            },
            data: {
                "email" : document.getElementById("email").value
            },
            datatype: "JSON",
            success: function(data) {
                alert("전송되었습니다!");
                location.reload();
            },
            error: function(error) {
                //로그인이 필요한 경우.
                if(error.status == 401){
                    alert("로그인을 해주세요.");
                    return;
                }
                alert(error.status + JSON.stringify(error.responseJSON));
            },
        });
    }
</script>

drf_jwt/templates/includes/system/header.html
{% load static %}
<!-- ======= Header ======= -->
 <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'system_manage:home' %}" class="logo d-flex align-items-center">
        {% comment %} <img src="{% static 'system/assets/img/logo.png' %}" alt=""> {% endcomment %}
        <span class="d-none d-lg-block">HappySong Admin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item dropdown pe-3">
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">

            <span class="d-none d-md-block dropdown-toggle p-2">{{user}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{user}}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'website:home' %}">
                <i class="bi bi-house"></i>
                <span>Website</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex align-items-center" href="javascript:;" onclick="logout();">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

drf_jwt/templates/includes/system/sidebar.html
 <!-- ======= Sidebar ======= -->
 <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'system_manage:home' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-layout-text-window-reverse"></i><span>System Manage</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'system_manage:access_manage' %}">
              <i class="bi bi-circle"></i><span>Access Manage</span>
            </a>
          </li>
          <li>
            <a href="{% url 'system_manage:permission_manage' %}">
              <i class="bi bi-circle"></i><span>Permission Manage</span>
            </a>
          </li>
        </ul>
      </li><!-- End Tables Nav -->
    </ul>

  </aside><!-- End Sidebar-->

drf_jwt/templates/includes/website/header.html
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'website:home' %}">Happy Song</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

drf_jwt/templates/includes/website/sections/hero.html
{% load static %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

    <div class="container">
        <div class="row">
        <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
            <h1 data-aos="fade-up">Gift a Happy Song to someone you love.</h1>
            <h2 data-aos="fade-up" data-aos-delay="400">We are team of talented AI Experts making Happy Song</h2>
            <div data-aos="fade-up" data-aos-delay="800">
            <a href="{% url 'website:test' %}" class="btn-get-started scrollto">Get Started</a>
            </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left" data-aos-delay="200">
            <img src="{% static 'website/assets/img/hero-img.png' %}" class="img-fluid animated" alt="">
        </div>
        </div>
    </div>

</section><!-- End Hero -->

drf_jwt/website/templates/website_index.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block stylesheets %}
<style>
.btn-custom {
  background: #3498db;
  padding: 8px 25px;
  margin-left: 30px;
  border-radius: 50px;
  color: #fff;
}
.btn-custom:hover {
  color: #fff;
  background: #4aa3df;
}
</style>
{% endblock stylesheets %}


{% block main %}
<main id="main" class="main">
    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
  
          <div class="d-flex justify-content-between align-items-center">
            <h2>Inner Page</h2>
            <ol>
              <li><a href="{% url 'website:home' %}">Home</a></li>
              <li>Inner Page</li>
            </ol>
          </div>
  
        </div>
      </section><!-- End Breadcrumbs Section -->
  
      <section class="inner-page">
        <div class="container">
          <p>
            Example inner page template
          </p>
        </div>
      </section>
</main>
{% endblock %}

{% block javascripts %}{% endblock javascripts %}

drf_jwt/website/templates/website_test.html
{% extends "layouts/website_base.html" %}
{% load static %}

{% block stylesheets %}
<style>
.btn-custom {
  background: #3498db;
  padding: 8px 25px;
  margin-left: 30px;
  border-radius: 50px;
  color: #fff;
}
.btn-custom:hover {
  color: #fff;
  background: #4aa3df;
}
</style>
{% endblock stylesheets %}


{% block main %}
<main id="main" class="main">
    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
          <div class="d-flex justify-content-between align-items-center">
            <h2>Generate Song</h2>
            <ol>
              <li><a href="{% url 'website:home' %}">Home</a></li>
              <li>Generate Song</li>
            </ol>
          </div>
        </div>
      </section><!-- End Breadcrumbs Section -->

      <section class="inner-page">
        <div class="container">
          <p>
            Receive a Happy Song by email !
          </p>
          <div class="row gy-4 mt-3">
            <div class="row justify-content-center">
              <div class="col-6" >
                <input class="form-control" id="email" name="email" placeholder="Input your Email">
              </div>
            </div>
            <div class="text-center">
              <a class="btn-custom text-center" type="button" id="btn-submit" href="javascript:;">전송</a>
            </div>
          </div>
        </div>
      </section>
</main>
{% endblock %}

{% block javascripts %}
<script src="{% static 'website/js/script_test.js' %}"></script>
{% endblock javascripts %}